// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8DlmdCF5gCs5Dyu8kV5MEf2NkvM8O2jE',
    appId: '1:728639701348:web:29d23e047031e40d5e3a71',
    messagingSenderId: '728639701348',
    projectId: 'notifications-779ae',
    authDomain: 'notifications-779ae.firebaseapp.com',
    storageBucket: 'notifications-779ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUFtZ6RitkRhZtLw9hiQZVDozt52ZZ-7g',
    appId: '1:728639701348:android:0efab1df78cdc1c65e3a71',
    messagingSenderId: '728639701348',
    projectId: 'notifications-779ae',
    storageBucket: 'notifications-779ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRC52RBb53Dru6RidU3T9dJy3CeMhpPJo',
    appId: '1:728639701348:ios:0193507b46ff9aaf5e3a71',
    messagingSenderId: '728639701348',
    projectId: 'notifications-779ae',
    storageBucket: 'notifications-779ae.appspot.com',
    iosClientId: '728639701348-l9g3dtson72lnpon1bqpdk53b56qgtoa.apps.googleusercontent.com',
    iosBundleId: 'mn.et24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRC52RBb53Dru6RidU3T9dJy3CeMhpPJo',
    appId: '1:728639701348:ios:0193507b46ff9aaf5e3a71',
    messagingSenderId: '728639701348',
    projectId: 'notifications-779ae',
    storageBucket: 'notifications-779ae.appspot.com',
    iosClientId: '728639701348-l9g3dtson72lnpon1bqpdk53b56qgtoa.apps.googleusercontent.com',
    iosBundleId: 'mn.et24',
  );
}
